# https://taskfile.dev

version: '3'
vars:
  ARTIFACT_DIRECTORY: ./artifacts

tasks:
  default:
    cmds:
      - task --list
    silent: true
  init:
    desc: initialize project tooling and directories
    cmds:
    - |
      mkdir -p {{ .ARTIFACT_DIRECTORY }}
      chmod -R a+rwx ./artifacts
      go mod tidy
  build:
    desc: build app
    cmds:
    - |
      rm ./artifacts/backlinker
      go build -o ./artifacts/backlinker
  test:
    desc: run go tests
    cmds:
      - task: build
      - |
        go test -v
